name: Github Preview Nuget

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/norison/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution [Release]
        run: dotnet build --no-restore -c Release -p:VersionSuffix=$GITHUB_RUN_NUMBER

      - name: Pack solution [Release]
        run: dotnet pack --no-restore --no-build -c Release -p:VersionSuffix=$GITHUB_RUN_NUMBER -o PackOutputs

      - name: Publish Nuget package
        run: dotnet nuget push "PackOutputs/*" -k ${{secrets.GITHUB_TOKEN}}